# Generated by Django 4.1.4 on 2023-01-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="color",
            field=models.CharField(
                choices=[
                    ("Slate", "SLATE"),
                    ("Gray", "GRAY"),
                    ("Zinc", "ZINC"),
                    ("Neutral", "NEUTRAL"),
                    ("Stone", "STONE"),
                    ("Red", "RED"),
                    ("Orange", "ORANGE"),
                    ("Amber", "AMBER"),
                    ("Yellow", "YELLOW"),
                    ("Lime", "LIME"),
                    ("Green", "GREEN"),
                    ("Emerald", "EMERALD"),
                    ("Teal", "TEAL"),
                    ("Cyan", "CYAN"),
                    ("Sky", "SKY"),
                    ("Blue", "BLUE"),
                    ("Indigo", "INDIGO"),
                    ("Violet", "VIOLET"),
                    ("Purple", "PURPLE"),
                    ("Fuchsia", "FUCHSIA"),
                    ("Pink", "PINK"),
                    ("Rose", "ROSE"),
                ],
                max_length=55,
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(
                choices=[
                    ("Web Design", "WEB DESIGN"),
                    ("Tailwind.css", "TAILWIND.CSS"),
                    ("TypeScript", "TYPESCRIPT"),
                    ("Next.js", "NEXT.JS"),
                    ("Blog", "BLOG"),
                    ("JavaScript", "JAVASCRIPT"),
                    ("Astro.js", "ASTRO.JS"),
                    ("Bootstrap", "BOOTSTRAP"),
                ],
                max_length=55,
            ),
        ),
    ]
