# Generated by Django 4.2.6 on 2023-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_rename_technology_stacks_project_stacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(
                choices=[
                    ("Css", "CSS"),
                    ("Html", "HTML"),
                    ("Bootstrap", "BOOTSTRAP"),
                    ("Python", "PYTHON"),
                    ("Django", "DJANGO"),
                    ("JavaScript", "JAVASCRIPT"),
                    ("React.js", "REACT.JS"),
                    ("TypeScript", "TYPESCRIPT"),
                    ("Tailwind.css", "TAILWIND.CSS"),
                    ("Blog", "BLOG"),
                    ("Astro.js", "ASTRO.JS"),
                ],
                max_length=55,
            ),
        ),
    ]
